server:
  port: 7777   #端口7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB           #有关文件上传大小
      max-request-size: 5MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql日志
  global-config:
    db-config:
      logic-delete-field: delFlag  #逻辑删除字段
      logic-delete-value: 1        #1表示逻辑已删除
      logic-not-delete-value: 0    #0表示逻辑未删除
      id-type: auto                #id增长类型为自增